# 端口
server:
  port: 80
# 配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pethome
    username: root
    password: root
  redis:
    host: localhost #连接redis的主机ip
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 30 #给定时间可以分配的最大连接数。 使用负值表示没有限制
        maxIdle: 30  #最大空闲连接数
        minIdle: 10 # 最小空间连接数
        maxWait: -1 #连接池最大等待时间 -1没有限制
# 日志打印
logging:
  level:
    com:
      zfl19:debug
